[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
roulette_table = "ErfuhJxxpHNKviT5LCnupGhSUbXpjfRThxikEgb94aDt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "target/deploy/deployer-keypair.json"

[workspace]
members = ["programs/roulette_table"]
exclude = ["programs/vendor"]

[scripts]
test = "npx mocha -r ts-node/register/transpile-only --extension ts -t 1000000 tests/**/*.ts"
