[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false
no-idl = true

[programs.devnet]
roulette_table = "AV5r5GYG7adU9q1ojmyawExGtx2BAAqhtWa2AAXLNVa8"

[provider]
cluster = "devnet"
wallet = "target/deploy/deployer-keypair.json"

[scripts]
test = "npx mocha -t 1000000 tests/**/*.ts"
